-- MySQL Script generated by MySQL Workbench
-- Wed Aug 29 03:26:45 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema waterworks2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema waterworks2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `waterworks2` DEFAULT CHARACTER SET utf8 ;
USE `waterworks2` ;

-- -----------------------------------------------------
-- Table `waterworks2`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `waterworks2`.`Client` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `accountNumber` VARCHAR(45) NULL,
  `meterSerialNumber` VARCHAR(45) NULL,
  `firstName` VARCHAR(45) NULL,
  `lastName` VARCHAR(45) NULL,
  `middleInitial` VARCHAR(45) NULL,
  `mobileNumber` VARCHAR(45) NULL,
  `rateClass` VARCHAR(45) NULL,
  `businessArea` VARCHAR(45) NULL,
  `streetAddress` VARCHAR(45) NULL,
  `barangay` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `postalCode` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `accountNumber_UNIQUE` (`accountNumber` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `waterworks2`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `waterworks2`.`User` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(16) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `role` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NULL,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `middleInitial` VARCHAR(45) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `waterworks2`.`Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `waterworks2`.`Employee` (
  `id` INT NOT NULL,
  `firstName` VARCHAR(45) NULL,
  `lastName` VARCHAR(45) NULL,
  `area` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `waterworks2`.`BillingRate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `waterworks2`.`BillingRate` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `rate` FLOAT NOT NULL DEFAULT 0,
  `created_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `waterworks2`.`Collection`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `waterworks2`.`Collection` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Client_id` INT NOT NULL,
  `waterUsage` INT NULL,
  `totalAmount` DOUBLE NULL,
  `created_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `dueDate` DATE NULL,
  `isPaid` TINYINT NULL,
  `Employee_id` INT NOT NULL,
  `Teller_id` INT NOT NULL,
  `billingRate_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Employee_id`, `Teller_id`, `billingRate_id`),
  INDEX `fk_Collection_Customer_idx` (`Client_id` ASC),
  INDEX `fk_Collection_Employee1_idx` (`Employee_id` ASC),
  INDEX `fk_Collection_User1_idx` (`Teller_id` ASC),
  INDEX `fk_Collection_BillingRate1_idx` (`billingRate_id` ASC),
  CONSTRAINT `fk_Collection_Customer`
    FOREIGN KEY (`Client_id`)
    REFERENCES `waterworks2`.`Client` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Collection_Employee1`
    FOREIGN KEY (`Employee_id`)
    REFERENCES `waterworks2`.`Employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Collection_User1`
    FOREIGN KEY (`Teller_id`)
    REFERENCES `waterworks2`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Collection_BillingRate1`
    FOREIGN KEY (`billingRate_id`)
    REFERENCES `waterworks2`.`BillingRate` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
